import tkinter as tk
def cd(imail): pass
root = tk.Tk()
root.geometry('1920x1080')
text = tk.Text(root, height=800, width=40)
scroll = tk.Scrollbar(root)
text.configure(yscrollcommand=scroll.set)
text.pack(side=tk.LEFT)
scroll.config(command=text.yview)
scroll.pack(side=tk.LEFT, fill=tk.Y)
maillist = open('db/maillist.csv','r').read()
text.insert(tk.END,maillist)
imail = tk.Text(height=1,width=40)
imail.pack(side=tk.RIGHT)
cdbtn = tk.Button(text='Deşifrele', onclick=cd(imail.get))
cdbtn.pack(side=tk.RIGHT)
cdlabel = tk.Label(text="Bilgilerini deşifrelemek istediğiniz mail'i girin")
yenirzvsyn = tk.Button(text='Yeni Otel Kaydı Oluştur')
kayıtsil = tk.Button(text='Kayıt Sil')
btn2 = tk.Button(text='Buton1')
btn3 = tk.Button(text='Buton2')
btn1 = tk.Button(text='Buton3')

btn1.place(x=1790,y=350)
btn2.place(x=1710,y=350)
btn3.place(x=1790,y=400)
kayıtsil.place(x=1710,y=400)
yenirzvsyn.place()

cdlabel.place(x=1660, y=480)
root.mainloop()
